name: static-checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: load all project Node dependencies
        run: npm install
      - name: run lint
        run: npm run lint

  run-jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: load all project Node dependencies
        run: npm install
      - name: run unit tests
        run: npm run test

  run-tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: load all project Node dependencies
        run: npm install
      - name: run typescript compiler
        run: npx tsc
